// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HanziData struct {
	ID          string `json:"id"`
	Simplified  string `json:"simplified"`
	Pinyin      string `json:"pinyin"`
	Traditional string `json:"traditional"`
	Japanese    string `json:"japanese"`
	JundaFreq   *int   `json:"jundaFreq"`
	GsNum       *int   `json:"gsNum"`
	HskLvl      *int   `json:"hskLvl"`
}
